### ISSUE TITLE
BUG #006

### ISSUE THREAD

**Issue by kmeiz524** [Social-Study/social-study#24]
For the flashcard collection there should be a semi colon after "updated" and "today" should be capitalized.
https://www.screencast.com/t/V6XXpn90dZlR

**Comment by evan-buss** [comment]
It's supposed to be more like "natural" language. Instead of just "Label: Info". That's why I show the last updated as "today" or "1 day ago" instead of using regular 1/31/19 date format. If it looks awkward we can change it but it is intended lol.
